language: R
cache: packages
r_binary_packages:
 - testthat
warnings_are_errors: false
env:
 global:
  secure: "GsdTxPfEj6sm1RWMwl/AwUzKSkmbmFFh4k5zvR4LQfuGrjPolimG0A0pN+a5YOtfLi6jHdplBfzDJWw6sZAHE1i/LhaCDkiP3EjgaKTcs28JmhgqoD7x1LKEMm5WnMQhI0fl/PnMJYBJREt0Lub34tfcB+eZoRF2vrzJBuPhbLQYMMWQsln75xvu+28Cf4EoZivaTu6clpXgZ8iwEEn7pkNmQC4EfXtgbq069a1+S/R5EzHhBz+IyFL88q39i/0yMmNhM5GPPlAcFJNYh2PnxIpJoUlI8qXXq7b9le+DGBLHDjZ8RwQKEOWlLD0s8dNa39JnTPPX6hu8XqlRfm2jdxvYGOgNpykF5RvyO93+7sZ7UUeHHo91/ghT7NdNzitAJE8C+8bOy3/fcco5HkZBXtzOBHZuh9Dc+1BYyOZF9TLp2NfS4dCZZErH3T9dhGmTW0XICe1ffAEeNCX8xLy94Iv9dCcJ0FMQ2H4qbGPBDXUjbnz8xDA803PcIqc8I7eVSSfJzSHeUcadTNON1mMUmWQDHmAJ42IXJWTlMpFTDbyT/SuElvM14DFmXhI979rAzHtwvp/3HCQN5SJl/MmX1pv0YIAjb3jRL8z+LEHE/WeZoSvrtnpN6F/+6UyAvZzsjzeaBw6RCb33QHcKUD/OVg84GwGvQzPsnJJVDURYorc="
before_script: chmod +x update-json-index.sh
after_success: ./update-json-index.sh

